# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bce5a78c4516be770ded3560754d90470119042c94651bf1ef46225e4835ed9e8e2d5ee95056af25da990efe2386d55bb7a008ea3ebd4b45e9464fa3e36c9b2

test:
  secret_key_base: e2f1ceba628519c06e8a10ecc128cfa44971af11ccd112a842722b0cb1dfaf967d096465b3f2afe292bb7c6dc7d77b2862f503d7454c8106b63ebab6b77d4fbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
